### ISSUE TITLE
好像这个项目弃坑了

### ISSUE THREAD

**Issue by wushendutang** [CeuiLiSA/Pixiv-Slinky#12]

**Comment by Nachogao** [comment]
等等看吧

**Comment by LoxiaLiSA** [comment]
作者投资失败亏了200w CNY，已经破产归零，正在艰难度日

**Comment by mashirozx** [comment]
摸摸头

**Comment by Nachogao** [comment]
> 作者投资失败亏了200w CNY，已经破产归零，正在艰难度日

啊！

**Comment by wushendutang** [comment]
> 作者投资失败亏了200w CNY，已经破产归零，正在艰难度日

啊？

**Comment by LoxiaLiSA** [comment]
早该死了，也完全不怕死，但是觉得自己先走一步，对不住自己的父母。一定要给他们养老，不能让最亲近的人受最大的伤

**Comment by CeuiLiSA** [comment]
<img width="605" alt="image" src="https://github.com/CeuiLiSA/Pixiv-Slinky/assets/32817377/0c1e45c9-3b1f-41a9-9641-16a75e8d8b38">

**Comment by SoxiaLiSA** [comment]
被美国人卡脖子了，一直审核不过

**Comment by CeuiLiSA** [comment]
更新：被拒了，正在按要求修改再送审

**Comment by CeuiLiSA** [comment]
<img width="1200" alt="image" src="https://github.com/CeuiLiSA/Pixiv-Slinky/assets/32817377/0cf84679-ad63-4bfa-9eb7-13df17ef4cca">

**Comment by jainylord** [comment]
赞美老哥！

**Comment by CeuiLiSA** [comment]
https://play.google.com/store/apps/details?id=ceui.lisa.slinky
